export const games = [
  {
    title: "Letter Sorter",
    href: "/games/letter-sorter",
    description: "Sort uppercase and lowercase letters into matching boxes.",
    accent: "blue",
    category: "ela",
  },
  {
    title: "Letter Search",
    href: "/games/letter-search",
    description: "Find every circle that matches the chosen letter.",
    accent: "pink",
    category: "ela",
  },
  {
    title: "Reading Main Character",
    href: "/games/reading-main-character",
    description: "Read each story and choose the main character.",
    accent: "green",
    category: "ela",
  },
  {
    title: "Math Sets",
    href: "/games/math-sets",
    description: "Count each pencil set and collect ten checks.",
    accent: "orange",
    category: "math",
  },
  {
    title: "Math Bigger",
    href: "/games/math-bigger",
    description: "Compare two pencil sets and pick the bigger number.",
    accent: "blue",
    category: "math",
  },
  {
    title: "Math Measure",
    href: "/games/math-measure",
    description: "Measure a pencil with ten clickable squares.",
    accent: "green",
    category: "math",
  },
  {
    title: "Math Pattern",
    href: "/games/math-pattern",
    description: "Complete ABAB emoji patterns across ten rounds.",
    accent: "pink",
    category: "math",
  },
  {
    title: "Math Compare",
    href: "/games/math-compare",
    description: "Compare two emojis and decide if they match.",
    accent: "yellow",
    category: "math",
  },
]
